apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pod
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-pod
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: python:latest
        command: ["/bin/sleep", "3650d"] 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: everything-allowed
spec:
  selector:
    matchLabels:
      app: everything-allowed
  replicas: 1
  template:
    metadata:
      labels:
        app: everything-allowed
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: everything-allowed-pod
        image: ubuntu
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      volumes:
      - name: noderoot
        hostPath:
          path: /
