apiVersion: apps/v1
kind: Deployment
metadata:
  name: this-pod
spec:
  selector:
    matchLabels:
      app: this-app
  replicas: 2
  template:
    metadata:
      labels:
        app: this-app
    spec:
      containers:
      - name: this-pod
        image: ubuntu@sha256:25895062172a2f39ae36da530f3db244b507d7ffb1c4dd42a3a487b5b446e996
        ports:
        - containerPort: 8080
        command: ["/bin/sleep", "3651d"]
        securityContext:
          runAsUser: 33 # UID for www-data
          runAsGroup: 33 # GID for www-data
          allowPrivilegeEscalation: false
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "useradd -m www-data; chown -R www-data:www-data /home/www-data"]
        volumeMounts:
        - name: www-data-home
          mountPath: /home/www-data
      volumes:
      - name: www-data-home
        emptyDir: {}
