apiVersion: apps/v1
kind: Deployment
metadata:
  name: this-pod
spec:
  selector:
    matchLabels:
      app: this-app
  replicas: 2
  template:
    metadata:
      labels:
        app: this-app
    spec:
      containers:
      - name: this-pod
        image: cycodelabs/argocd-exploit-ubuntu:latest
        ports:
        - containerPort: 8080
        command: ["/bin/bash", "-c", "sleep 3651d"]
